FROM bioconductor/bioconductor_docker:RELEASE_3_13

LABEL SOFTWARE_NAME csdemux v0.0.6
LABEL MAINTAINER "Tom Harrop"
LABEL VERSION "csdemux v0.0.6"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

RUN     apt-get clean && \
        rm -r /var/lib/apt/lists/*

RUN     . /etc/os-release \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME} main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-updates main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-backports main restricted universe multiverse" >> mirror.txt && \
        echo "deb mirror://mirrors.ubuntu.com/mirrors.txt ${UBUNTU_CODENAME}-security main restricted universe multiverse" >> mirror.txt && \
        mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        cat mirror.txt /etc/apt/sources.list.bak > /etc/apt/sources.list && \
        apt-get update && apt-get upgrade -y --fix-missing

RUN     apt-get update && apt-get install -y  --no-install-recommends \
            build-essential \
            default-jre-headless \
            git \
            pigz \
            wget

RUN     Rscript -e "options(Ncpus=8); \
        BiocManager::install(c( \
            'bit64', \
            'Cairo', \
            'data.table', \
            'future.apply', \
            'ggplot2', \
            'scales', \
            'viridis' \
        ))"

# bbmap install
RUN     mkdir /bbmap && \
        wget -O "/bbmap.tar.gz" \
            --no-check-certificate \
            https://sourceforge.net/projects/bbmap/files/BBMap_38.90.tar.gz &&\
        tar -zxf /bbmap.tar.gz \
            -C /bbmap \
            --strip-components 1

RUN     cp -r /bbmap/resources/* / && \
        cp -r /bbmap/* /usr/local/bin/

RUN     rm -r /bbmap /bbmap.tar.gz

# install pipeline package
RUN     /usr/bin/python3.8 -m pip \
            install --upgrade pip && \
        /usr/bin/python3.8 -m pip \
            install --upgrade setuptools wheel && \
        /usr/bin/python3.8 -m pip \
            install \
            git+git://github.com/tomharrop/csdemux.git@v0.0.6


ENTRYPOINT ["/usr/local/bin/csdemux"]
